const characterData = [
    {
        "id": 1,
        "name": "阿格莱雅",
        "group": "A",
        "gender": "female",
        "desc": "谎言，纤毫毕现。生命，脆若游丝。万缕千丝，在我指尖。",
        "desc_mobile": "偶然与意外，独具美感",
        "image": "agelaiya.png",
        "image_popular": "agelaiya.png",
        "votes": 0
    },
    {
        "id": 2,
        "name": "艾丝妲",
        "group": "A",
        "gender": "female",
        "desc": "了解的事越多，我就越喜欢这片星空",
        "desc_mobile": "一切，都是星辰的选择",
        "image": "aisida.png",
        "image_popular": "aisida.png",
        "votes": 0
    },
    {
        "id": 3,
        "name": "阿兰",
        "group": "A",
        "gender": "male",
        "desc": "这点疼痛不足挂齿。而敌人将会，痛苦万倍！",
        "desc_mobile": "活着，才能继续战斗",
        "image": "alan.png",
        "image_popular": "alan.png",
        "votes": 0
    },
    {
        "id": 4,
        "name": "白厄",
        "group": "A",
        "gender": "male",
        "desc": "亿万火种之怒，燃尽此身。赐你，众星俱焚的曙光",
        "desc_mobile": "亿万火种之怒，燃尽此身",
        "image": "baie.png",
        "image_popular": "baie.png",
        "votes": 0

    },
    {
        "id": 5,
        "name": "白露",
        "group": "A",
        "gender": "female",
        "desc": "既不说话又不动，我们都是木头人~",
        "desc_mobile": "这葫芦里卖的什么药",
        "image": "bailu.png",
        "image_popular": "bailu.png",
        "votes": 0
    },
    {
        "id": 6,
        "name": "波提欧",
        "group": "A",
        "gender": "male",
        "desc": "世上只有两种人——要么手枪上膛…要么自掘坟墓！",
        "desc_mobile": "该开枪就别说废话",
        "image": "botiou.png",
        "image_popular": "botiou.png",
        "votes": 0
    },
    {
        "id": 7,
        "name": "布洛妮娅",
        "group": "A",
        "gender": "female",
        "desc": "筑城者砌成堡垒，使我们远离风雪，但必须铭记，风雪从未消失",
        "desc_mobile": "铭记，风雪从未消失",
        "image": "buluoniya.png",
        "image_popular": "buluoniya.png",
        "votes": 0
    },
    {
        "id": 8,
        "name": "不死途",
        "group": "A",
        "gender": "male",
        "desc": "献出我血，吞没不义… 恶兽们，来，开始自相残杀吧！",
        "desc_mobile": "恶兽们，开始自相残杀吧",
        "image": "busitu.png",
        "image_popular": "busitu.png",
        "votes": 0
    },
    {
        "id": 9,
        "name": "大丽花",
        "group": "A",
        "gender": "female",
        "desc": "记忆的坟茔，已然敞开，曲终人亡时，美不胜收",
        "desc_mobile": "记忆的坟茔，已然敞开",
        "image": "dalihua.png",
        "image_popular": "dalihua.png",
        "votes": 0
    },
    {
        "id": 10,
        "name": "丹恒",
        "group": "B",
        "gender": "male",
        "desc": "生死虚实，一念之间。洞天幻化，长梦一觉",
        "desc_mobile": "已经结束的过去并不重要",
        "image": "danheng.png",
        "image_popular": "danheng.png",
        "votes": 0
    },
    {
        "id": 11,
        "name": "翡翠",
        "group": "B",
        "gender": "female",
        "desc": "协定已成。以此为据，也就再无反悔的余地… 你我都是",
        "desc_mobile": "总该有第二手准备",
        "image": "feicui.png",
        "image_popular": "feicui.png",
        "votes": 0
    },
    {
        "id": 12,
        "name": "飞霄",
        "group": "B",
        "gender": "female",
        "desc": "我将，巡征追猎。翾翔不坠，万载常胜！",
        "desc_mobile": "大捷，已定！",
        "image": "feixiao.png",
        "image_popular": "feixiao.png",
        "votes": 0
    },
    {
        "id": 13,
        "name": "绯英",
        "group": "B",
        "gender": "female",
        "desc": "神鬼无赦！",
        "desc_mobile": "神鬼无赦！",
        "image": "feiying.png",
        "image_popular": "feiying.png",
        "votes": 0
    },
    {
        "id": 14,
        "name": "风堇",
        "group": "B",
        "gender": "female",
        "desc": "愿这一抹微光… 拨开阴翳与云雾，重见澄澈晴空！",
        "desc_mobile": "拨开云雾，重见晴空！",
        "image": "fengjin.png",
        "image_popular": "fengjin.png",
        "votes": 0
    },
    {
        "id": 15,
        "name": "符玄",
        "group": "B",
        "gender": "female",
        "desc": "世间万物自有其法… 但换斗移星，谋事，在人！",
        "desc_mobile": "以额间之眼观之…",
        "image": "fuxuan.png",
        "image_popular": "fuxuan.png",
        "votes": 0
    },
    {
        "id": 16,
        "name": "桂乃芬",
        "group": "B",
        "gender": "female",
        "desc": "瞧一瞧看一看了哎！机会难得，给您拜个早年吧！",
        "desc_mobile": "给您拜个早年吧！",
        "image": "guinaifen.png",
        "image_popular": "guinaifen.png",
        "votes": 0
    },
    {
        "id": 17,
        "name": "寒鸦",
        "group": "B",
        "gender": "female",
        "desc": "幽府判罚，命尔臂助… 十王敕令，在此成书",
        "desc_mobile": "有差事没办完…又还阳",
        "image": "hanya.png",
        "image_popular": "hanya.png",
        "votes": 0
    },
    {
        "id": 18,
        "name": "黑塔/大黑塔",
        "group": "B",
        "gender": "female",
        "desc": "好奇心，可是很危险的。谜题千千万万，但谜底却是…乌有之物",
        "desc_mobile": "好奇心，可是很危险的",
        "image": "heita.png",
        "image_popular": "heita.png",
        "votes": 0
    },
    {
        "id": 19,
        "name": "海瑟音",
        "group": "C",
        "gender": "female",
        "desc": "嘘，请在此驻足静听，这场深海欢宴中，来自各位的悲鸣",
        "desc_mobile": "嘘，请在此驻足静听",
        "image": "haiseyin.png",
        "image_popular": "haiseyin.png",
        "votes": 0
    },
    {
        "id": 20,
        "name": "黑天鹅",
        "group": "C",
        "gender": "female",
        "desc": "记忆是常变的泡沫。静默的水面下…便是无尽深渊",
        "desc_mobile": "命运，并非一种选择",
        "image": "heitiane.png",
        "image_popular": "heitiane.png",
        "votes": 0
    },
    {
        "id": 21,
        "name": "花火/火花",
        "group": "C",
        "gender": "female",
        "desc": "来捉迷藏呀。愚者千面，游戏人间…你，会找到答案么？",
        "desc_mobile": "我们现在可是一伙的~",
        "image": "huahuo.png",
        "image_popular": "huahuo.png",
        "votes": 0
    },
    {
        "id": 22,
        "name": "黄泉",
        "group": "C",
        "gender": "female",
        "desc": "我为逝者哀哭… 暮雨，终将落下",
        "desc_mobile": "流淌吧，过往的刀光",
        "image": "huangquan.png",
        "image_popular": "huangquan.png",
        "votes": 0
    },
    {
        "id": 23,
        "name": "虎克",
        "group": "C",
        "gender": "female",
        "desc": "我来了…我又走咯~ 诶嘿嘿…没想到吧？",
        "desc_mobile": "你说谁是小家伙",
        "image": "huke.png",
        "image_popular": "huke.png",
        "votes": 0
    },
    {
        "id": 24,
        "name": "藿藿",
        "group": "C",
        "gender": "female",
        "desc": "藿藿：非、非得战斗吗？尾巴：对喽~别逃啊~",
        "desc_mobile": "你、你们不要过来啊",
        "image": "huohuo.png",
        "image_popular": "huohuo.png",
        "votes": 0
    },
    {
        "id": 25,
        "name": "加拉赫",
        "group": "C",
        "gender": "male",
        "desc": "生命醇美如佳酿。朋友们，尽情享用吧！",
        "desc_mobile": "生命醇美如佳酿",
        "image": "jialahe.png",
        "image_popular": "jialahe.png",
        "votes": 0
    },
    {
        "id": 26,
        "name": "椒丘",
        "group": "C",
        "gender": "male",
        "desc": "承蒙诸位赏脸… 来都来了，不如吃过再走",
        "desc_mobile": "文火慢熬抑或武火爆炒",
        "image": "jiaoqiu.png",
        "image_popular": "jiaoqiu.png",
        "votes": 0
    },
    {
        "id": 27,
        "name": "杰帕德",
        "group": "C",
        "gender": "male",
        "desc": "我以朗道之名。历经冰雪，铸成此志，永不终结！",
        "desc_mobile": "铸成此志，永不终结！",
        "image": "jiepade.png",
        "image_popular": "jiepade.png",
        "votes": 0
    },
    {
        "id": 28,
        "name": "镜流",
        "group": "D",
        "gender": "female",
        "desc": "就让这一轮月华… 照彻万川！",
        "desc_mobile": "照彻万川！",
        "image": "jingliu.png",
        "image_popular": "jingliu.png",
        "votes": 0
    },
    {
        "id": 29,
        "name": "景元",
        "group": "D",
        "gender": "male",
        "desc": "该出奇兵了。煌煌威灵，遵吾敕命。斩无赦！",
        "desc_mobile": "该出奇兵了",
        "image": "jingyuan.png",
        "image_popular": "jingyuan.png",
        "votes": 0
    },
    {
        "id": 30,
        "name": "姬子",
        "group": "D",
        "gender": "female",
        "desc": "我想，你可能还不明白…人类从不掩饰掌控星空的欲望…也包括我在内",
        "desc_mobile": "要来喝一杯咖啡吗",
        "image": "jizi.png",
        "image_popular": "jizi.png",
        "votes": 0
    },
    {
        "id": 31,
        "name": "卡芙卡",
        "group": "D",
        "gender": "female",
        "desc": "美妙的时光总有尽头。该说再见了…",
        "desc_mobile": "美妙的时光总有尽头",
        "image": "kafuka.png",
        "image_popular": "kafuka.png",
        "votes": 0
    },
    {
        "id": 32,
        "name": "克拉拉",
        "group": "D",
        "gender": "female",
        "desc": "我也想保护大家… 帮帮我，史瓦罗先生！",
        "desc_mobile": "帮帮我史瓦罗先生！",
        "image": "kelala.png",
        "image_popular": "kelala.png",
        "votes": 0
    },
    {
        "id": 33,
        "name": "刻律德菈",
        "group": "D",
        "gender": "female",
        "desc": "败者成灰，胜者为王… 我以律法之名宣判，汝等，满盘皆输",
        "desc_mobile": "败者成灰，胜者为王…",
        "image": "kelvdela.png",
        "image_popular": "kelvdela.png",
        "votes": 0
    },
    {
        "id": 34,
        "name": "玲可",
        "group": "D",
        "gender": "female",
        "desc": "为了去往远方… 不管什么手段，通通拿出来吧！",
        "desc_mobile": "想去做的话就去做",
        "image": "lingke.png",
        "image_popular": "lingke.png",
        "votes": 0
    },
    {
        "id": 35,
        "name": "灵砂",
        "group": "D",
        "gender": "female",
        "desc": "金鳞燃犀，洞若观火。世间种种…不过是过眼云烟",
        "desc_mobile": "世间种种，过眼云烟",
        "image": "lingsha.png",
        "image_popular": "lingsha.png",
        "votes": 0
    },
    {
        "id": 36,
        "name": "流萤",
        "group": "D",
        "gender": "female",
        "desc": "我将，点燃星海！飞萤扑火，向死而生",
        "desc_mobile": "飞萤扑火，向死而生",
        "image": "liuying.png",
        "image_popular": "liuying.png",
        "votes": 0
    },
    {
        "id": 37,
        "name": "乱破",
        "group": "E",
        "gender": "female",
        "desc": "银河忍法，千变万化。此乃「忍法•奥义•缭乱灭破杀阵」",
        "desc_mobile": "斩！断！破！",
        "image": "luanpo.png",
        "image_popular": "luanpo.png",
        "votes": 0
    },
    {
        "id": 38,
        "name": "卢卡",
        "group": "E",
        "gender": "male",
        "desc": "欢呼声在哪儿？值得我认真起来的对手…见识下火花四溅吧！",
        "desc_mobile": "见识下火花四溅吧",
        "image": "luka.png",
        "image_popular": "luka.png",
        "votes": 0
    },
    {
        "id": 39,
        "name": "罗刹",
        "group": "E",
        "gender": "male",
        "desc": "永眠非终焉… 逝者将再临！",
        "desc_mobile": "凡夺取的，必将偿还",
        "image": "luocha.png",
        "image_popular": "luocha.png",
        "votes": 0
    },
    {
        "id": 40,
        "name": "米沙",
        "group": "E",
        "gender": "male",
        "desc": "不知道时间还剩多少… 又、又要来不及了呜啊啊啊——！",
        "desc_mobile": "不知时间还剩多少…",
        "image": "misha.png",
        "image_popular": "misha.png",
        "votes": 0
    },
    {
        "id": 41,
        "name": "貊泽",
        "group": "E",
        "gender": "male",
        "desc": "该收割了。风声所到之处…你无所遁形！",
        "desc_mobile": "幽冥，奔袭！",
        "image": "moze.png",
        "image_popular": "moze.png",
        "votes": 0
    },
    {
        "id": 42,
        "name": "那刻夏",
        "group": "E",
        "gender": "male",
        "desc": "世界的真理，我已解明。至是，工程已毕，言尽于此",
        "desc_mobile": "魔术技巧！",
        "image": "nakexia.png",
        "image_popular": "nakexia.png",
        "votes": 0
    },
    {
        "id": 43,
        "name": "娜塔莎",
        "group": "E",
        "gender": "female",
        "desc": "看来是赶上了。一点心意而已，不必在意",
        "desc_mobile": "感受生命的冲击",
        "image": "natasha.png",
        "image_popular": "natasha.png",
        "votes": 0
    },
    {
        "id": 44,
        "name": "佩拉",
        "group": "E",
        "gender": "female",
        "desc": "敌方数据收集完毕。收网标记激活，接下来就是愉快的反击时间了",
        "desc_mobile": "这样…然后这样…",
        "image": "peila.png",
        "image_popular": "peila.png",
        "votes": 0
    },
    {
        "id": 45,
        "name": "青雀",
        "group": "E",
        "gender": "female",
        "desc": "让我摸个鱼吧！拜托拜托拜托…哎呀，这不就…和了！",
        "desc_mobile": "让我摸个鱼吧",
        "image": "qingque.png",
        "image_popular": "qingque.png",
        "votes": 0
    },
    {
        "id": 46,
        "name": "刃",
        "group": "F",
        "gender": "male",
        "desc": "此番美景，我虽求而不得… 却能，邀诸位共赏",
        "desc_mobile": "此番美景邀诸位共赏",
        "image": "ren.png",
        "image_popular": "ren.png",
        "votes": 0
    },
    {
        "id": 47,
        "name": "阮·梅",
        "group": "F",
        "gender": "female",
        "desc": "生命里的每一片花瓣… 无论何时盛放，都会有被风吹落的… 那一天",
        "desc_mobile": "仍有值得研究的价值",
        "image": "ruanmei.png",
        "image_popular": "ruanmei.png",
        "votes": 0
    },
    {
        "id": 48,
        "name": "赛飞儿",
        "group": "F",
        "gender": "female",
        "desc": "随便玩玩的把戏结束了~ 一人传虚，万人传实。骗到你咯~",
        "desc_mobile": "一人传虚，万人传实",
        "image": "saifeier.png",
        "image_popular": "saifeier.png",
        "votes": 0
    },
    {
        "id": 49,
        "name": "桑博",
        "group": "F",
        "gender": "male",
        "desc": "你在期待些什么？顾客就是上帝，想要我背叛上帝，除非…你加钱~",
        "desc_mobile": "我桑博一向关照朋友",
        "image": "sangbo.png",
        "image_popular": "sangbo.png",
        "votes": 0
    },
    {
        "id": 50,
        "name": "三月七/长夜月",
        "group": "F",
        "gender": "female",
        "desc": "是时候展现真正的剑术了。左青龙，右白虎，少吃碳水化合物——看招！",
        "desc_mobile": "要陪我去拍照吗",
        "image": "sanyueqi.png",
        "image_popular": "sanyueqi.png",
        "votes": 0
    },
    {
        "id": 51,
        "name": "砂金",
        "group": "F",
        "gender": "male",
        "desc": "骰子已经掷下。一无所有？或者，赢下所有！",
        "desc_mobile": "骰子已经掷下",
        "image": "shajin.png",
        "image_popular": "shajin.png",
        "votes": 0
    },
    {
        "id": 52,
        "name": "素裳",
        "group": "F",
        "gender": "female",
        "desc": "吃我一招，太虚形蕴！凤凰，显形！",
        "desc_mobile": "吃我一招，太虚形蕴",
        "image": "sushang.png",
        "image_popular": "sushang.png",
        "votes": 0
    },
    {
        "id": 53,
        "name": "缇宝",
        "group": "F",
        "gender": "female",
        "desc": "要、来、了！预备，起—— 缇宝&缇安&缇宁：乘着西风，出发咯~",
        "desc_mobile": "乘着西风，出发咯",
        "image": "tibao.png",
        "image_popular": "tibao.png",
        "votes": 0
    },
    {
        "id": 54,
        "name": "停云",
        "group": "F",
        "gender": "female",
        "desc": "前尘旧梦，俱已往矣。生命纵如微尘，亦能翩然起舞",
        "desc_mobile": "前尘旧梦，俱已往矣",
        "image": "tingyun.png",
        "image_popular": "tingyun.png",
        "votes": 0
    },
    {
        "id": 55,
        "name": "托帕",
        "group": "G",
        "gender": "female",
        "desc": "行情扑朔迷离… 目光放远，聚焦长线…就是投资成功的秘诀！",
        "desc_mobile": "目光放远，聚焦长线",
        "image": "tuopa.png",
        "image_popular": "tuopa.png",
        "votes": 0
    },
    {
        "id": 56,
        "name": "瓦尔特",
        "group": "G",
        "gender": "male",
        "desc": "见识一下星辰粉碎的样子吧…生存还是毁灭，你别无选择",
        "desc_mobile": "接下来就交给我吧",
        "image": "waerte.png",
        "image_popular": "waerte.png",
        "votes": 0
    },
    {
        "id": 57,
        "name": "万敌",
        "group": "G",
        "gender": "male",
        "desc": "垂死之魂，直面我！我允许你们…伏首受诛！",
        "desc_mobile": "向我展现你的勇气",
        "image": "wandi.png",
        "image_popular": "wandi.png",
        "votes": 0
    },
    {
        "id": 58,
        "name": "遐蝶",
        "group": "G",
        "gender": "female",
        "desc": "拥抱「新生」吧，玻吕刻斯。惟愿「死亡」…捍卫你我！",
        "desc_mobile": "我会铭记此刻的温度",
        "image": "xiadie.png",
        "image_popular": "xiadie.png",
        "votes": 0
    },
    {
        "id": 59,
        "name": "希儿",
        "group": "G",
        "gender": "female",
        "desc": "这就让你解脱。随蝴蝶一起消散吧，旧日的幻影",
        "desc_mobile": "随蝴蝶一起消散吧",
        "image": "xier.png",
        "image_popular": "xier.png",
        "votes": 0
    },
    {
        "id": 60,
        "name": "昔涟",
        "group": "G",
        "gender": "female",
        "desc": "记忆的涟漪，等待被流星唤醒— 用「爱」铭记，在那美丽的明天",
        "desc_mobile": "无论过去多久，我都会等你",
        "image": "xilian.png",
        "image_popular": "xilian.png",
        "votes": 0
    },
    {
        "id": 61,
        "name": "希露瓦",
        "group": "G",
        "gender": "female",
        "desc": "准备好释放自己了么？不管是反抗，摇摆，沉沦，都将…",
        "desc_mobile": "跟上，我的节奏！",
        "image": "xiluwa.png",
        "image_popular": "xiluwa.png",
        "votes": 0
    },
    {
        "id": 62,
        "name": "星期日",
        "group": "G",
        "gender": "male",
        "desc": "以此身躯… 与你同道，护你左右，领你远行",
        "desc_mobile": "与你同道，领你远行",
        "image": "xingqiri.png",
        "image_popular": "xingqiri.png",
        "votes": 0
    },
    {
        "id": 63,
        "name": "雪衣",
        "group": "G",
        "gender": "female",
        "desc": "承十王敕… 入魔，必诛！",
        "desc_mobile": "承十王敕，入魔必诛",
        "image": "xueyi.png",
        "image_popular": "xueyi.png",
        "votes": 0
    },
    {
        "id": 64,
        "name": "彦卿",
        "group": "H",
        "gender": "male",
        "desc": "试探就到此为止了。万剑，天来！",
        "desc_mobile": "万剑，天来！",
        "image": "yanqing.png",
        "image_popular": "yanqing.png",
        "votes": 0
    },
    {
        "id": 65,
        "name": "爻光",
        "group": "H",
        "gender": "female",
        "desc": "世人总道天意难违… 本座偏要，执此一签，观照诸天",
        "desc_mobile": "执此一签，观照诸天",
        "image": "yaoguang.png",
        "image_popular": "yaoguang.png",
        "votes": 0
    },
    {
        "id": 66,
        "name": "银狼LV.999",
        "group": "H",
        "gender": "female",
        "desc": "不装了，接下来这把——高端局！",
        "desc_mobile": "不装了，接下来这把高端局",
        "image": "yinlang.png",
        "image_popular": "yinlang.png",
        "votes": 0
    },
    {
        "id": 67,
        "name": "银枝",
        "group": "H",
        "gender": "male",
        "desc": "再次见到那道光芒之前… 银河中的一切美丽，我将捍卫至最后一刻",
        "desc_mobile": "…献给伊德莉拉",
        "image": "yinzhi.png",
        "image_popular": "yinzhi.png",
        "votes": 0
    },
    {
        "id": 68,
        "name": "驭空",
        "group": "H",
        "gender": "female",
        "desc": "风起，云鸢就位。只此，一箭！",
        "desc_mobile": "风起，云鸢就位",
        "image": "yukong.png",
        "image_popular": "yukong.png",
        "votes": 0
    },
    {
        "id": 69,
        "name": "云璃",
        "group": "H",
        "gender": "female",
        "desc": "碎——岩——破！崩——剑——斩！",
        "desc_mobile": "截云断岳，剑出山倾",
        "image": "yunli.png",
        "image_popular": "yunli.png",
        "votes": 0
    },
    {
        "id": 70,
        "name": "真理医生",
        "group": "H",
        "gender": "male",
        "desc": "存在即被感知… 知识既为万物尺度，定将穷尽真理、根除谬误",
        "desc_mobile": "穷尽真理、根除谬误",
        "image": "zhenliyisheng.png",
        "image_popular": "zhenliyisheng.png",
        "votes": 0
    },
    {
        "id": 71,
        "name": "知更鸟",
        "group": "H",
        "gender": "female",
        "desc": "今夜，灵魂彼此相拥。今夜，群星因我回响",
        "desc_mobile": "愿你在歌中寻得安宁",
        "image": "zhigengniao.png",
        "image_popular": "zhigengniao.png",
        "votes": 0
    }
]