proxy_api_url: http://api.shenlongproxy.com/ip?cty=&c=30&pt=1&ft=txt&pat=\r\n&rep=1&key=1879eb7e&ts=5
proxy_protocol: http
target_character_name: 砂金
target_character_names:
- 砂金
- 卡芙卡
- 那刻夏
target_button_index: 10
concurrency: 6
total_votes: 20000
debug_mode: false
flow_mode: quick
user_cookies: ''
flaresolverr_url: ''
captcha_mode: auto2
yydsocr_token: ''
browser_engine: chromium
browser_path: C:\Program Files\Google\Chrome\Application\chrome.exe
headless: false
last_resolved_name: 砂金
last_resolved_index: 0
last_resolved_at: '2026-05-18 17:34:54'
captcha_offset_x: -352
captcha_offset_y: -178
