proxy_api_url: http://api.shenlongproxy.com/ip?cty=&c=30&pt=1&ft=txt&pat=\r\n&rep=1&key=1879eb7e&ts=5
proxy_protocol: http
target_character_name: 大丽花
target_button_index: 19
concurrency: 1
total_votes: 200
browser_engine: chromium
browser_path: C:\Program Files\Google\Chrome\Application\chrome.exe
headless: false
last_resolved_name: 大丽花
last_resolved_index: 19
last_resolved_at: '2026-05-09 22:03:19'
